name: Check for new manifest
on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Update pip
        run: python -m pip install --upgrade pip
      
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.1.3
        with:
          poetry-version: '1.1.12'
      
      - name: Install Environment
        run: poetry install --no-dev
      
      - name: Check for manifest version
        run: poetry run python check_for_manifest.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
          PAT: ${{ secrets.PAT }}
          LOG_LEVEL: "INFO"
      
      - name: Check for new files
        id: data
        run: echo ::set-output name=porcelain::"$(git status --porcelain)"

      - name: Commit latest manifest version
        if: steps.data.outputs.porcelain
        uses: stefanzweifel/git-auto-commit-action@v4.7.2
        with:
          commit_message: new manifest version
          commit_user_name: D2 Manifest Bot
          commit_user_email: 1605206150tq@gmail.com
          commit_author: D2 Manifest Bot <1605206150tq@gmail.com>
