name: learn-github-actions
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - run: python --version
      
      - name: Update pip
        run: |
          python -m pip install --upgrade pip
      
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.1.3
        with:
          poetry-version: '1.1.12'
        run: poetry -V
        run: poetry install --no-dev
        run: poetry env list
      
      - name: Check for manifest version
        run: poetry run python check_for_manifest.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
          LOG_LEVEL: "INFO"
