name: learn-github-actions
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - run: python --version
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
#       - name: Check for manifest update
#         run: python manifest:check
#         env:
#           API_KEY: ${{ secrets.API_KEY }}
